name: M3U Com

on:  
  push:  
    paths:  
      - 'tv/**/*.txt'  # 当txt文件发生变化时触发  
  workflow_dispatch:  # 手动触发  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
               token: ${{ secrets.LIVELIST }}
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests futures eventlet opencv-python Beautifulsoup4 translate termcolor func_timeout replace input opencc pypinyin pytz tqdm
      - name: Run py
        run: | 
          python ${{ github.workspace }}/py/com_m3u.py      
      - name: 提交更改
        run: |
          git config --local user.email "actions@163.com"
          git config --local user.name "GitHub Action"
          #git reset --hard origin/main
          git add .
          git commit -m "Add generated file"
          #git commit *.txt -m "Add generated file"
          #git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
