name: Copy Files to Another  
  
on:    
  push:    
    paths:    
      - 'LB.txt'  # 当txt文件发生变化时触发    
  workflow_dispatch:  # 手动触发    
  
jobs:    
  copy-files:    
    runs-on: ubuntu-latest    
    
    steps:    
    - name: Checkout source repository    
      uses: actions/checkout@v2    
    
    - name: Set up Python    
      uses: actions/setup-python@v2    
      with:    
        python-version: '3.x'    
    
    - name: Install dependencies    
      run: |    
        python -m pip install --upgrade pip    
        pip install gitpython    
    
    - name: Clone target repository    
      env:    
        TARGET_REPO_URL: github.com/168xx/jdcj.git  # 替换为你的目标仓库URL    
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}  # 替换为你的目标仓库的PAT    
      run: |    
        git clone https://$GITHUB_ACTOR:$GITHUB_TOKEN@$TARGET_REPO_URL target-repo    
        cd target-repo    
        git config --local user.email "action@github.com"    
        git config --local user.name "github-actions"    
    
    - name: Copy .txt and .m3u files to target repository    
      run: |    
        cp -r $(pwd)/*.txt $(pwd)/*.m3u target-repo/live/    
    
    - name: Add, commit, and force push changes    
      run: |    
        cd target-repo    
        git add live/    
        if [ -n "$(git status --porcelain)" ]; then    
          git commit -m "Automated update of .txt and .m3u files"    
          git push -f origin HEAD:168xx/jdcj/live  # 使用强制推送更新目标分支    
        fi